# ============================================================================
# COOLIFY - Deployment-Konfiguration für Pump Discover
# ============================================================================
#
# Diese Datei ist für Coolify optimiert:
#   - Web (UI): Port 8500
#   - API (Relay): Port 8010
#   - Named Volumes für Persistenz
#   - Kein Docker Socket (Coolify-kompatibel)
# ============================================================================

services:
  # ============================================================================
  # API Service (Relay) - Port 8010
  # ============================================================================
  api:
    build:
      context: ./relay
      dockerfile: Dockerfile
    container_name: pump-discover-relay
    restart: unless-stopped
    environment:
      - BATCH_SIZE=${BATCH_SIZE:-10}
      - BATCH_TIMEOUT=${BATCH_TIMEOUT:-30}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL:-}
      - N8N_WEBHOOK_METHOD=${N8N_WEBHOOK_METHOD:-POST}
      - WS_RETRY_DELAY=${WS_RETRY_DELAY:-3}
      - WS_MAX_RETRY_DELAY=${WS_MAX_RETRY_DELAY:-60}
      - N8N_RETRY_DELAY=${N8N_RETRY_DELAY:-5}
      - WS_PING_INTERVAL=${WS_PING_INTERVAL:-20}
      - WS_PING_TIMEOUT=${WS_PING_TIMEOUT:-10}
      - WS_CONNECTION_TIMEOUT=${WS_CONNECTION_TIMEOUT:-30}
      - WS_URI=${WS_URI:-wss://pumpportal.fun/api/data}
      - BAD_NAMES_PATTERN=${BAD_NAMES_PATTERN:-test|bot|rug|scam|cant|honey|faucet}
      - HEALTH_PORT=8000
    ports:
      # API & Metrics Port für Coolify
      # Externer Port: 8010 → Interner Port: 8000
      # Endpoints: http://your-domain:8010/health und http://your-domain:8010/metrics
      - "8010:8000"
    volumes:
      # Named Volume für Config (Coolify-kompatibel)
      - config_data:/app/config:rw
    networks:
      - pump-discover-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # ============================================================================
  # Web Service (Streamlit UI) - Port 8500
  # ============================================================================
  web:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: pump-discover-ui
    restart: unless-stopped
    environment:
      - RELAY_SERVICE=api
      - RELAY_PORT=8000
      # Coolify: Service-Name für interne Kommunikation
      # Der Service 'api' ist über das interne Netzwerk erreichbar
      - COOLIFY_MODE=true
      # Coolify: Kein Docker Socket verfügbar, daher deaktivieren wir Docker-Features
    ports:
      # Streamlit UI Port für Coolify
      # Externer Port: 8500 → Interner Port: 8501
      # URL: http://your-domain:8500
      - "8500:8501"
    volumes:
      # Named Volume für Config (geteilt mit API)
      - config_data:/app/config:rw
    networks:
      - pump-discover-network
    depends_on:
      - api

networks:
  pump-discover-network:
    driver: bridge

volumes:
  # Named Volume für Config-Daten (Coolify-kompatibel)
  config_data:
